[package]
name = "urap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.1"
embedded-io = "0.6.1"
[features]
default = ["std", "usockets"]
std = ["embedded-io/std"]
usockets = ["std"]
